### ISSUE TITLE
Problems with android, works in osx

### ISSUE THREAD

**Issue by arhplanet** [payfriendz/cordova-plugin-jumio#1]
Hi there. 

There are problems with the plugin on android. it reports class not found. Any Ideas?

**Comment by chriswessels** [comment]
Hi there @arhplanet! Unfortunately we no longer support this plugin as we've replaced Cordova with a React Native based strategy. If you're working on a greenfield project, we'd suggest you take a look at RN. That being said, if you find a solution, we'd happily accept a PR.

Best,
Chris

**Comment by arhplanet** [comment]
Thanks chris! I figured it out 

You need to change the namespace

use com.phonegap.plugins.jumio

Arne

**Comment by chriswessels** [comment]
Great, glad to hear @arhplanet.
